version: 2.1
jobs:
  build:
    docker:
      -image: golang: latest
    working_directory: /gosrc/github.com/jonatasgome1/devOps
    steps:
      - checkout
      - run: 
        name: Run tests
        command: go test -v
